#!/bin/bash

seeds=$(python3 get_primes.py --nums 1 200)

M=50000 # action space size
d=12 # dimension of "mapped" features
k=10 # dimension of "latent" features
half=$((k / 2))
almost=$((k - 1))
feat_bound=1
sigma=0.1
param_bound=1
T=50000 # total horizon
# K=15
delta=0.00001
TRIALS=3 # number of trials
lambda=1

echo "Partial Mode"
IFS=','
# for seed in "${seeds[@]}"; do
# for seed in {350..399}; do
for seed in $seeds; do
    echo "Context Noise is 0"
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 15 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles 1 --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $half --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --num_visibles $almost --horizon $T --seed "$seed" --feat_dist uniform --feat_uniform_rng -0.5 0.5 --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist gaussian --map_upper_bound 1 --context_std 0 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    
    # echo "Context Noise is 1 over sqrt(T)"
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist gaussian --check_specs --delta $delta

    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist gaussian --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta

    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles 1 --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $half --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
    # python test_linhop.py --trials $TRIALS --action_spaces $M --num_actions 10 20 30 40 --obs_dim $d --latent_dim $k --lbda $lambda --num_visibles $almost --horizon $T --seed "$seed" --feat_dist gaussian --feat_disjoint --latent_feature_bound 1 --obs_feature_bound 1 --latent_bound_method scaling --map_dist uniform --map_upper_bound 1 --context_std T-0.5 --reward_std 0.1 --param_dist uniform --param_bound 1 --param_disjoint --bias_dist uniform --check_specs --delta $delta
done
